<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientMFA</name>
   <tag></tag>
   <elementGuidId>c452b4d8-909c-42e9-b233-d32db2ff099c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;otp&quot;] > span > #swap-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='swap-input'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form #swap-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b69e252b-60e0-4623-ac08-9498132294d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1c7b5d2f-b941-4516-b394-d0d9af08fc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>aff07bdf-b1cb-46f6-bad2-f8eeecda28f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e48a559e-be6a-4c12-aa57-350c4f386918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>23df4f7e-12a5-410d-a9ea-a51e7bc3bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>59d1d0d4-48f4-4894-b1e6-80a907e4968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>58cdc56c-40a6-4afa-b1d8-5f7993c13762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>797a4776-c8b2-440f-a7a3-922dce590bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d{6}$/</value>
      <webElementGuid>57acd7bd-66c8-4a22-89c0-59403f4c7186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog inline-padding modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/v-verify[1]/form[@class=&quot;mt-3 ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;margin-block-16&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>b7ed7cde-a820-414e-ba05-35ef829c45bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[2]</value>
      <webElementGuid>3c5eb7fd-00eb-4335-b767-f32e202f0304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/sw-input/span/input</value>
      <webElementGuid>d2450ccf-7a9e-4ff4-aaf2-fa058bdddc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text']</value>
      <webElementGuid>e835b8e9-e59b-41a4-a7bd-cf14ab6ba0fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
