<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MFA_ContinueBtn</name>
   <tag></tag>
   <elementGuidId>50fe8e7b-47d7-4971-bae8-fe153f71ca0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sw-btn.sw-btn-primary.sw-btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Continue&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a478ee9-9c6c-4195-b4cd-4bfcb7022afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>77b90aa0-b971-4fa1-827c-50821daf2dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ce68291f-4350-495a-92f9-87e64b3d4aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-btn sw-btn-primary sw-btn-block</value>
      <webElementGuid>b9013f02-ae11-4aa5-9ce9-f5fb286b8e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>1e4caba7-ba15-4622-ac31-63c82de79952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog inline-padding modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/v-verify[1]/form[@class=&quot;mt-3 ng-untouched ng-star-inserted ng-dirty ng-valid&quot;]/div[@class=&quot;margin-block-16&quot;]/sw-button[1]/button[@class=&quot;sw-btn sw-btn-primary sw-btn-block&quot;]</value>
      <webElementGuid>1c08ab11-bc82-4764-8278-53fed461953c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>146b6d3b-10e1-4d83-b5c3-25a5c4c7cac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile authenticator code'])[1]/following::button[1]</value>
      <webElementGuid>4784572a-2823-49a2-867e-f84ec08b2f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mobile authenticator'])[1]/following::button[1]</value>
      <webElementGuid>e0c9fe03-4bd8-4fcf-9797-77f6cee1e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try another method.'])[1]/preceding::button[1]</value>
      <webElementGuid>c419462a-3ed1-4803-b067-b961b6aaa5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/sw-button/button</value>
      <webElementGuid>962baea6-32cd-44db-8d8a-23732efad738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7944dee7-fb01-44eb-afe4-59ed494df9f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
