<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bank_name</name>
   <tag></tag>
   <elementGuidId>c85eb3c9-80f9-4e4b-9cbe-3d4f6883d640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/div/sw-card/div/sw-card-body/div/form/div[3]/ng-select/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dceb5b33-938c-4bb6-bc2b-e25631c85026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e02ff56c-6a83-4d86-9469-f74a888feca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91eb8475-5d7d-4058-b413-ea81be9e1308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32a258b8-375d-4e8e-94a1-566697bd4b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fbcf8159-45fc-4948-8495-40d4bf8bb623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a492e71cb2b5</value>
      <webElementGuid>e09f087c-0c77-4a81-a55e-9fe7ca5062dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a492e71cb2b5-3</value>
      <webElementGuid>b9af89f7-26ad-41e9-8edc-03bf28bcda0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>a492e71cb2b5</value>
      <webElementGuid>37ac8574-4859-400e-99b7-433aaf7adc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-body&quot;)/div[@class=&quot;padding-16 ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[2]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;bg-white padding-16 radius-lg ng-star-inserted&quot;]/sw-card[1]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100 margin-block-16&quot;]/form[@class=&quot;ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;ng-star-inserted&quot;]/ng-select[@class=&quot;swap-dropdown ng-select-searchable ng-select ng-select-single ng-untouched ng-pristine ng-invalid ng-select-focused ng-select-opened ng-select-bottom&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>04b1788e-95c4-481c-a0a8-628fdc69cc80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>45de85c0-5e61-4ea6-9e58-dd273e4237e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/div/sw-card/div/sw-card-body/div/form/div[3]/ng-select/div/div/div[3]/input</value>
      <webElementGuid>b9514d6a-2a8e-4fc3-ae79-744e9c880ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b72c223c-460c-4469-8126-947a47324ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>1927fd39-5268-4135-9ee6-c07a7d4ecad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
