<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cancel_button</name>
   <tag></tag>
   <elementGuidId>2f54ab12-1212-45e2-b0c8-49f7e98eed92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sw-button[type=&quot;button&quot;] > button.sw-btn.sw-btn-secondary > span.sw-btn-label.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>393fc01d-c85f-40a4-a8fd-3879f47faac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-btn-label ng-star-inserted</value>
      <webElementGuid>20f20cec-deda-48b3-8b07-7f21b4bf2694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>21fde656-44ac-4813-9bbd-780d150b35f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog animate_slideInRight full-screen modal-content-md modal-md sidenav-modal&quot;]/div[@class=&quot;modal-content&quot;]/v-add-beneficiary-v4[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/v-sidepanel[1]/div[@class=&quot;sidepanel-wrapper&quot;]/div[@class=&quot;sidepanel-footer background-white padding-16 ng-star-inserted&quot;]/div[@class=&quot;footer-button ng-star-inserted&quot;]/div[@class=&quot;flex flex-wrap gaps-8&quot;]/div[@class=&quot;flex ng-star-inserted&quot;]/div[@class=&quot;margin-inline-8&quot;]/sw-button[1]/button[@class=&quot;sw-btn sw-btn-secondary&quot;]/span[@class=&quot;sw-btn-label ng-star-inserted&quot;]</value>
      <webElementGuid>4a92731b-873c-4fd0-a836-0ac7472d511a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/following::span[1]</value>
      <webElementGuid>2a6915b2-05da-4b67-b54a-b357188bcbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/following::span[2]</value>
      <webElementGuid>47ea7881-95eb-4027-af9f-633ba19fd559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>bf00e223-890d-4433-aa46-8a242a6d6359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/sw-button/button/span</value>
      <webElementGuid>365c2b9e-5fcc-401f-9b1a-2c43cdeb7c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>11d6b3ab-a31a-4ffb-a71d-d361a3e4f9d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
