<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_icon</name>
   <tag></tag>
   <elementGuidId>aaeca510-084c-4d32-b489-69c48320b760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidepanel-header']/div/div[2]/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sds-delete.sw-btn-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;p&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1f2761c-efe6-435d-ae7f-7dc5b17ac739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26eaa7f0-9464-4c85-930d-debebb88776c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sds-delete sw-btn-icon</value>
      <webElementGuid>23d8f2b1-8efd-486c-a250-555ac34ced0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-header&quot;)/div[@class=&quot;flex flex-grow space-between bg-white padding-16 radius-lg ng-star-inserted&quot;]/div[@class=&quot;flex flex-wrap align-items-center gaps-10 ng-star-inserted&quot;]/button[@class=&quot;sw-btn sw-btn-gray sw-btn-sm sw-btn-icon-only ng-star-inserted&quot;]/span[@class=&quot;sds-delete sw-btn-icon&quot;]</value>
      <webElementGuid>84566228-ebf3-4ed5-9942-35bff2c62f48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-header']/div/div[2]/button[2]/span</value>
      <webElementGuid>f88c2524-52a1-46b9-a1ff-04378dba2e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>f2f509dd-d066-4449-a752-b02b5134f58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
