<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Senegal</name>
   <tag></tag>
   <elementGuidId>528d23e1-4198-4bfe-af97-740e7e846092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a00b82e90048-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'a00b82e90048-163' and (text() = 'Senegal' or . = 'Senegal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Senegal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4af2e6fb-6622-4afa-a5d9-c4c066bac9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>b4abd8bf-c07f-4e83-ab92-eaf37f595091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b3ec8577-df5f-4c59-a7b8-de471b830a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4490d09-7f50-481e-b515-1406bfbee6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a00b82e90048-163</value>
      <webElementGuid>4e8a5795-4cdf-43f5-a203-9911029369b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senegal</value>
      <webElementGuid>a12c5af2-645d-4ad2-8f20-cf425d1f2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a00b82e90048-163&quot;)</value>
      <webElementGuid>e84a50e2-c3db-45ea-8572-ba7a4900b828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a00b82e90048-163']</value>
      <webElementGuid>5cd6b4f5-6376-4838-810d-c36d4b811f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a00b82e90048']/div/div[2]/div</value>
      <webElementGuid>e291a1f7-ba3b-4a9b-8b7c-a3baf294f302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select country'])[1]/following::div[6]</value>
      <webElementGuid>ee756ef6-1177-48fc-83f3-b9d7f109dd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient country*'])[1]/following::div[9]</value>
      <webElementGuid>e40e8214-ac67-44df-ac97-2840a6c69e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient State*'])[1]/preceding::div[1]</value>
      <webElementGuid>cc18ec9b-a86c-4158-a922-d05c0cbdb1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>c3648618-70c6-42d7-b6cd-e35fb3c593b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a00b82e90048-163' and (text() = 'Senegal' or . = 'Senegal')]</value>
      <webElementGuid>3b60ada1-0c7c-4ac8-ad08-b0bda7caefac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
