<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter_amount_to_Send_toBeneficiary</name>
   <tag></tag>
   <elementGuidId>d1e5c3a6-f1f5-45fd-8500-b53bbe47fbd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='send-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#send-id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0ced74b-db43-4a62-aaa7-0585ce013159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>28ecc915-bb2f-42f1-aab5-c33ddad5cd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send-id</value>
      <webElementGuid>4fd3fd32-6ed7-4be5-adfb-ddf40eb00fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4840d001-7050-4aca-9155-30a878916f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Amount</value>
      <webElementGuid>4c07e7c4-6e4b-4ace-bfa7-8ed7d9dd75a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab9ba3b9-6476-4ac2-adfa-db88ab05f481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>5c1bfa2a-b4c9-4eb8-a284-cbef0ee2cf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>92d7e571-4ac1-4797-a5f5-27efafc78933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f16b8c18-8bc8-4488-8a49-5e9d4b069db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*[1-9])\d*(?:\.\d+)?$</value>
      <webElementGuid>172bd93d-b964-4d33-a3e5-021025ae727b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send-id&quot;)</value>
      <webElementGuid>074e306a-efb9-4026-bb6f-09b41d98029c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='send-id']</value>
      <webElementGuid>b8b4545c-fc43-48f4-b644-f7cce6d0ce31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content/div[2]/div/v-choose-amount/sw-card/div/sw-card-body/div/div/div/div/div/div[3]/sw-input/span/input</value>
      <webElementGuid>037a57af-ffd5-4970-9f9d-c4d4dc8a1153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/sw-input/span/input</value>
      <webElementGuid>88ef8fd1-c1ea-4998-bba5-8d004a236b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'send-id' and @type = 'number' and @placeholder = 'Enter Amount']</value>
      <webElementGuid>9d8ac8dd-0865-456a-a9b2-28aea4479ef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
