<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>individual_beneficiary</name>
   <tag></tag>
   <elementGuidId>c0e486e4-a230-4f6d-b9f5-8a6b48a25c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sw-radio-btn-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sw-radio-btn-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;An individual&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa1a4994-0000-4f9a-95e7-ce8a7f9a7001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>89864479-c1c1-442a-bbf1-accbbec8ea00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-radio-input</value>
      <webElementGuid>026f3e3d-d8d0-409c-a140-f4cb8a3b52bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sw-radio-btn-2</value>
      <webElementGuid>a69481e0-1bbb-46f9-9028-9883262ddd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beneficiaryTypeSelected</value>
      <webElementGuid>f9cbeaac-3c1b-4ada-8b91-eb8bb90140eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>50dbfd99-227d-46c1-a670-5eb9c5a29542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81c9f934-1d01-4773-9941-c08eca2487d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-radio-btn-2&quot;)</value>
      <webElementGuid>5a94c434-0ed5-42fa-92a1-23f266f606ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sw-radio-btn-2']</value>
      <webElementGuid>07858ae5-785b-4000-9e61-dce573051d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content/div[2]/div/sw-card/div/sw-card-body/div/sw-radio-group/div/div/div[2]/sw-radio-button/div/input</value>
      <webElementGuid>779fc0e9-6e1e-41e6-acf0-acc7bfc85ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sw-radio-button/div/input</value>
      <webElementGuid>d183de0d-3b92-4739-9f7a-d38f5639d055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'sw-radio-btn-2' and @name = 'beneficiaryTypeSelected']</value>
      <webElementGuid>c161154a-e7bd-43f9-9844-5f488644b972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
