<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank address</name>
   <tag></tag>
   <elementGuidId>6307e54f-9269-4a22-a957-69be1dad9f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='swap-input'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;bankAddress&quot;] > span > #swap-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caeaccea-abf9-4717-b45c-803ec3d5bfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>64e3f0db-2fdf-42d5-8932-df459c614a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>357dcc0a-a45d-4e6c-bcf9-0195835e2a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ae32b85-6ce9-4026-bda8-cdde28df8c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter address</value>
      <webElementGuid>294f187e-6d9b-4855-be2e-6ca0a54d04bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>7aa56385-6dd0-4add-8de2-7b3428a005f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>bbfaffc5-7efe-41b6-8d84-3e23dcf68e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>f94cde8d-8b96-4bca-a9fc-64605988af55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3315a67-fac4-4672-8736-e16d2eb1a721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(|[0-9a-zA-Z ]{0,35})$</value>
      <webElementGuid>078a4b33-d250-497d-9904-1febbbf8e3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-body&quot;)/div[@class=&quot;padding-16 ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[2]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;bg-white padding-16 radius-lg ng-star-inserted&quot;]/sw-card[1]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100 margin-block-16&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;margin-block-16&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>928d111b-2e2e-4352-a8dd-974542b4087c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[7]</value>
      <webElementGuid>809502d0-ad81-4d1e-ac9f-29b976f97463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/div/sw-card/div/sw-card-body/div/form/div[3]/div/div[4]/sw-input/span/input</value>
      <webElementGuid>32e4ce24-0ed1-4b67-ab38-6a2ec49760d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sw-input/span/input</value>
      <webElementGuid>2df430cf-2f8e-48be-9c60-6dfdb7e1258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text' and @placeholder = 'Enter address']</value>
      <webElementGuid>575a5526-2930-413f-9213-205426681a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
