<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make Payment_swap-input</name>
   <tag></tag>
   <elementGuidId>0289b79d-82ba-4df0-8d3c-d8062dbee1e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;currencyInput&quot;] > span > #swap-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='swap-input'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>v-currency-selector >> internal:has-text=&quot;I want to sendGBP&quot;i >> internal:attr=[placeholder=&quot;Enter Amount&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b5a4552-e76b-431e-ab91-353bd92069bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2191eb69-15e9-4143-bbc0-4a6907de744c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>2ad95c0d-e2c4-4bf0-883c-69056b680584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>931d5da6-c3e2-42ee-b2e3-02a619008da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Amount</value>
      <webElementGuid>39822457-779c-4a59-b8db-9614e95e352c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dae6a19a-3f7b-4a66-b532-43b6d840db85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>de1fb978-d3ce-4791-a296-5a0abcbf9a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>f0cdf6f2-43ca-4d28-ba2e-386a7c52f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>519e188b-c10f-43f7-ad49-611f42fe1fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d{1,3}(,\d{3})*(\.\d+)?$</value>
      <webElementGuid>c979789e-86b2-48ae-b104-5d2a63143f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog animate_slideInRight full-screen modal-content-xl modal-xl sidenav-modal&quot;]/div[@class=&quot;modal-content&quot;]/v-send-money-core[1]/v-sidepanel[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sidepanel-wrapper&quot;]/div[@id=&quot;sidepanel-body&quot;]/div[@class=&quot;panel-body isSidepanel ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[1]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;sw-card bg-gray-100 padding-32 ng-star-inserted&quot;]/v-choose-amount[1]/sw-card[1]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;amounts-boxes ng-star-inserted&quot;]/div[@class=&quot;send-section&quot;]/v-currency-selector[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sw-input currency-selector-wrapper currency-selector-wrapper-sidePanel bg-white&quot;]/div[@class=&quot;amount-div&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>6d00c6a1-8217-4246-b7a7-7a1bf65fa073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[2]</value>
      <webElementGuid>9596975e-e0d9-48a9-8eba-6b8f15e42ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content/div[2]/div/v-choose-amount/sw-card/div/sw-card-body/div/div/div/div/v-currency-selector/div/div[2]/sw-input/span/input</value>
      <webElementGuid>a7223e4e-cb10-4e74-9e41-459f6830b1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sw-input/span/input</value>
      <webElementGuid>487a843f-8e82-4c70-9199-2078b36a90fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text' and @placeholder = 'Enter Amount']</value>
      <webElementGuid>700c5ab2-c6a3-4952-ac1b-bbf3d9246c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
