<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ABA CodeRouting Number_USD</name>
   <tag></tag>
   <elementGuidId>ebeb5f24-38f6-44ff-bb23-3dd22f82745a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='swap-input'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;bankCode&quot;] > span > #swap-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>sw-input >> internal:has-text=&quot;ABA Code/Routing Number*&quot;i >> #swap-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86457edd-74b6-4f91-b9ca-0735d0ac44ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-pristine ng-valid ng-touched</value>
      <webElementGuid>03cb3c86-75b7-41f9-a2cd-185d7ca5ee1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>b99a7aee-81e1-492b-9c0e-aa4c1c21670d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49fd6fa4-6611-45e4-a4c4-517ee7590881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>21c75052-a3a9-4dc3-be2f-812775cde04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>d5c1b392-d981-4fa0-8ded-5f236f8be810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>efb00611-c8e4-40d5-97a5-444353a6da83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa4b4d0f-d569-4595-b27b-d3845f39d8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(|\w{9})$</value>
      <webElementGuid>8548e4a1-2b48-48ef-a873-59ac1fa7bb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-body&quot;)/div[@class=&quot;padding-16 ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[2]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;bg-white padding-16 radius-lg ng-star-inserted&quot;]/sw-card[1]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100 margin-block-16&quot;]/form[@class=&quot;ng-untouched ng-invalid ng-dirty&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;margin-block-16&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>932a3a81-0cf1-4247-b65a-269cfacc63ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[5]</value>
      <webElementGuid>eff0e79b-2c05-478a-a021-90b81526c8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/div/sw-card/div/sw-card-body/div/form/div[3]/div/div/sw-input/span/input</value>
      <webElementGuid>c9fd5fef-6665-40c7-9d14-513717a35601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/sw-input/span/input</value>
      <webElementGuid>302de845-dea7-43a9-90ec-3397816e5f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text']</value>
      <webElementGuid>54ad1308-1f78-49e4-9bb8-8bb8e6c10909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
