<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment Method_beneficiaryMode</name>
   <tag></tag>
   <elementGuidId>b18b71e5-56bc-4915-bdef-c80145e1ef38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sw-radio-btn-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sw-radio-btn-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;International Bank Transfer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>beee9651-ee74-4481-bece-dad37fb18664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>02a3d768-af39-405f-9c55-f9a13cd0085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-radio-input</value>
      <webElementGuid>af5af08c-51de-4bea-aedc-9e12d88d89ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sw-radio-btn-5</value>
      <webElementGuid>a155c294-160a-4fe1-bc6b-d0e1e4f50136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beneficiaryMode</value>
      <webElementGuid>c1335686-f15c-49db-a19b-849251b3e047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>INTERNATIONAL</value>
      <webElementGuid>5d98cf28-34b4-4767-a579-e074230f9900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2671e91-2e43-47b7-9da1-8a5990a9ecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>d0e7196b-8fa0-4f35-8712-3642aa5db790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-radio-btn-5&quot;)</value>
      <webElementGuid>47e708e0-13e7-48bd-b90e-c63bd3d23aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sw-radio-btn-5']</value>
      <webElementGuid>5904a27f-c5f1-43c0-bbec-18bfa7cc25d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sw-radio-group[@id='add-beneficary-popup-dd-mode']/div/div/div[2]/sw-radio-button/div/input</value>
      <webElementGuid>b3c3308e-67d0-4c5b-aeec-4181c51f8b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sw-card[2]/div/sw-card-body/div/sw-radio-group/div/div/div[2]/sw-radio-button/div/input</value>
      <webElementGuid>6538b195-004a-4dcb-a3a7-efb2df1ea736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'sw-radio-btn-5' and @name = 'beneficiaryMode']</value>
      <webElementGuid>ed948b7a-1845-446b-ad23-5b1e2f8de7d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
