<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KES_3</name>
   <tag></tag>
   <elementGuidId>c50f998d-a3f3-4a03-8f46-58082f621e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a6816cc3db5c-23 > div.flex.align-items-center.gaps-10.ng-star-inserted > p.text-mm.text-gray-600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a6816cc3db5c-23']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Options list&quot;i >> internal:text=&quot;KSh&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>95eaa463-58d3-4beb-84ad-4bef3d30efdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-mm text-gray-600</value>
      <webElementGuid>4bfad2a1-3ad7-4125-8720-5ef7e51db0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KSh</value>
      <webElementGuid>bbbf076a-c775-4c1b-b30e-5a3e3140fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a6816cc3db5c-23&quot;)/div[@class=&quot;flex align-items-center gaps-10 ng-star-inserted&quot;]/p[@class=&quot;text-mm text-gray-600&quot;]</value>
      <webElementGuid>07ce3103-7fbc-492f-86a3-fac9ba541613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a6816cc3db5c-23']/div/p</value>
      <webElementGuid>91904034-5062-4d9e-9f90-74a653b12ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the currency'])[1]/following::p[3]</value>
      <webElementGuid>60216c5b-b2e1-4c27-a86f-fa2d207346f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::p[5]</value>
      <webElementGuid>cd25dfab-3f98-48ad-b027-ae5d6113d881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary Type'])[1]/preceding::p[2]</value>
      <webElementGuid>ea095778-65cf-451a-bc43-33fafe421a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::p[5]</value>
      <webElementGuid>e2120007-fc25-46c7-afd3-287488f99895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div/p</value>
      <webElementGuid>ccd0810d-d8d1-416e-8f91-386432969651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'KSh' or . = 'KSh')]</value>
      <webElementGuid>5e5162cd-e81b-4551-980d-9a9b19377ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
