<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_country_Senegal</name>
   <tag></tag>
   <elementGuidId>5287db30-8bef-4cbd-954e-710cfee677c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aceb3b0a6c0f-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'aceb3b0a6c0f-163' and (text() = 'Senegal' or . = 'Senegal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Senegal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78245bae-81f4-4cd2-b4ab-3356b3a3d6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>267f84f6-559b-492f-8609-f99ee557b268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bb2221d1-b219-4628-b6bc-430610688238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86b85d3d-b8ce-4ad6-8af4-ec1ab607d287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aceb3b0a6c0f-163</value>
      <webElementGuid>8d21962b-0c18-4703-980e-aa3fbeb81f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senegal</value>
      <webElementGuid>d495d650-cea7-4cd2-bc9b-aa7bdc78f03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aceb3b0a6c0f-163&quot;)</value>
      <webElementGuid>5084df8d-a059-4937-928b-3d4b64189de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aceb3b0a6c0f-163']</value>
      <webElementGuid>86d80196-cc6b-4ea5-9647-1eb263208681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aceb3b0a6c0f']/div/div[2]/div</value>
      <webElementGuid>2980d291-1019-4b00-b22c-698a2747d4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select country'])[1]/following::div[5]</value>
      <webElementGuid>df272a6a-73d5-41fe-a023-1a473d9d953c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient country*'])[1]/following::div[8]</value>
      <webElementGuid>5b8f5598-aa67-4386-8dd3-73e9baf881e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient State*'])[1]/preceding::div[1]</value>
      <webElementGuid>88856c70-4ac9-4432-80c1-a82cde790625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>b66d46b0-e43d-450e-9061-e4a5ba1c3f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aceb3b0a6c0f-163' and (text() = 'Senegal' or . = 'Senegal')]</value>
      <webElementGuid>a369c51f-d0f8-4c2a-a854-d1f6b78d720e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
