<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KES_2</name>
   <tag></tag>
   <elementGuidId>d78f0bb8-26b6-4534-a9c9-f854533ec9ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-dropdown-panel-items.scroll-host</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-dropdown-panel[@id='a92c1cbfb68f']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Options list&quot;i >> internal:role=listbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>731ec16a-1f4b-4069-b996-a74b8c64d09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3255f0b2-c99b-47f0-98f5-ce52366c76b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-dropdown-panel-items scroll-host</value>
      <webElementGuid>f5a5f652-6e81-4755-bf24-51991534eec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KShKES</value>
      <webElementGuid>6cb9c221-bc4b-45f8-adac-13ef57aa9d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a92c1cbfb68f&quot;)/div[@class=&quot;ng-dropdown-panel-items scroll-host&quot;]</value>
      <webElementGuid>467eb6d7-c18b-4f7f-91ca-61b64014a8b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a92c1cbfb68f']/div</value>
      <webElementGuid>e8f71c6e-51bb-497a-acbc-fe2e05da228a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the currency'])[1]/following::div[4]</value>
      <webElementGuid>ea06faa2-f92b-47d1-9f41-ad06456a18a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[31]</value>
      <webElementGuid>6842a754-112b-4761-bbfc-f9316fa86ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary Type'])[1]/preceding::div[5]</value>
      <webElementGuid>21b4467c-227c-4e05-91f7-0e3ce889704d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[16]</value>
      <webElementGuid>2b3b3aea-9002-4459-ad47-b553e296c322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div</value>
      <webElementGuid>c6dbe074-71e4-4f35-a8d7-ce6c0989db78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KShKES' or . = 'KShKES')]</value>
      <webElementGuid>041a83da-5dd0-4c72-aa86-beebc71706c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
