<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KES_1</name>
   <tag></tag>
   <elementGuidId>57f5c3a7-1700-408f-85b7-0c430b2e5ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a3e4d08a8134-23 > div.flex.align-items-center.gaps-10.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'KShKES' or . = 'KShKES')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;KShKES&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d5b6fe9-9eca-4908-b26f-aa65cbfa16be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex align-items-center gaps-10 ng-star-inserted</value>
      <webElementGuid>0a10b8a2-afbc-427e-a64e-e9eb866e0830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KShKES</value>
      <webElementGuid>b8ba1ab0-72fa-4e2e-a711-6d4386787a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3e4d08a8134-23&quot;)/div[@class=&quot;flex align-items-center gaps-10 ng-star-inserted&quot;]</value>
      <webElementGuid>68afa487-704b-41c6-b893-e4b95a07285a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a3e4d08a8134-23']/div</value>
      <webElementGuid>1d41d830-9378-438a-a89d-9c9f79df329f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the currency'])[1]/following::div[6]</value>
      <webElementGuid>e702534f-1b91-4740-9579-f27e35f709a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[33]</value>
      <webElementGuid>aa438710-565b-4c50-8161-83dff7ac1cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary Type'])[1]/preceding::div[1]</value>
      <webElementGuid>f74b1f15-bae0-4af8-bc5c-cdc422cb8913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[12]</value>
      <webElementGuid>73f85a77-bb06-47d9-9af6-15ed7a1fa8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div</value>
      <webElementGuid>568cf96d-d22b-4381-a6e7-1f4a3d518ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KShKES' or . = 'KShKES')]</value>
      <webElementGuid>95b345aa-9f80-4c59-8106-52a2caa1fc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
