<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xof_Recipient_address_line_1</name>
   <tag></tag>
   <elementGuidId>70fb52aa-ec5b-430f-9dcd-b653ebfe1158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;beneficiaryAddress&quot;] > span > #swap-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'swap-input' and @type = 'text' and @placeholder = 'Enter address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Recipient address line 1\*$/ >> #swap-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bb5a4d3-69de-47b1-a6c9-a95c25f7b386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4a5bdb5c-ef2a-48fe-ab43-3ee953b3e661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>32f5cdb6-7924-4281-9ae3-362db9f448ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ba9edea-ac1d-4161-bafc-fde83c9da70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter address</value>
      <webElementGuid>792d25d6-20e9-43f9-bbf7-3973c5d12798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>a88a1167-6f19-4bee-9e45-8cf1d545025b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>a29df47c-7fa4-4e75-b263-60bd14f478d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>b621d26b-c062-4f2e-ad63-2bfee7d31d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>413bedd2-076b-4015-89e9-1243eb7e33f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(|[0-9a-zA-Z, ]{0,35})$</value>
      <webElementGuid>eb141bbf-7a60-4599-a8dc-b78063ec47dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-body&quot;)/div[@class=&quot;padding-16 ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;bg-white padding-16 radius-lg ng-star-inserted&quot;]/sw-card[1]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100 margin-block-16&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;margin-block-16&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>4e666b43-872e-4ad4-b96b-6798080bb388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[3]</value>
      <webElementGuid>8cf7444c-c99b-43e8-92ac-69e03cbeee43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[3]/div[2]/div/sw-card/div/sw-card-body/div/form/div[2]/sw-input/span/input</value>
      <webElementGuid>507bdd7e-7421-4413-a879-b72dff14f3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sw-input/span/input</value>
      <webElementGuid>4ab15329-a6de-4022-92ea-eed128f07562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text' and @placeholder = 'Enter address']</value>
      <webElementGuid>d46ba003-85c3-4466-957c-2a1d6607b0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
