<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_plan_change</name>
   <tag></tag>
   <elementGuidId>5bcb744b-baa1-4d06-84b1-350a9411f2ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sw-button.ng-star-inserted > button.sw-btn.sw-btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Continue and select plan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20b0ebf7-2381-4b79-8c32-f9c7c84df4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>81cbf389-be2c-4c3f-96d7-5071a11567ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue and select plan</value>
      <webElementGuid>be050460-fe30-4add-bd2d-fefc4be28024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-btn sw-btn-primary</value>
      <webElementGuid>f73eafa9-afc6-4fc2-8c14-9c23abbf403d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue and select plan</value>
      <webElementGuid>b57c117d-971d-410c-8539-d245a438d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog animate_slideInRight modal-content-sm modal-md sidenav-modal&quot;]/div[@class=&quot;modal-content&quot;]/v-change-plan-sidepanel[1]/v-sidepanel[1]/div[@class=&quot;sidepanel-wrapper&quot;]/div[@class=&quot;sidepanel-footer background-white padding-24 ng-star-inserted&quot;]/div[@class=&quot;footer-button ng-star-inserted&quot;]/sw-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;sw-btn sw-btn-primary&quot;]</value>
      <webElementGuid>d51a92e0-b107-4b6f-8928-a55f13fea3b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>4373470c-c82f-4d9d-aeef-1e49a1375309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[2]</value>
      <webElementGuid>4ffb0749-0893-4c30-9718-f5c385e01b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>03d27464-aa16-42b6-9879-feab405f6253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//v-sidepanel/div/div[3]/div/sw-button/button</value>
      <webElementGuid>1f05b3d6-5afd-4330-a993-77efd8f4e10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue and select plan' or . = 'Continue and select plan')]</value>
      <webElementGuid>50e64b72-c371-4969-89bc-e77e9d71511c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
