<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Purchase of Professional Service(s)</name>
   <tag></tag>
   <elementGuidId>f4962e0c-2766-466c-952e-1ba4e9d0f87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/form/div[2]/div/sw-select/div/div[2]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Purchase of Professional Service(s)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>628cc045-e582-4f17-8a40-354fcfd55ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>acef55b9-e9ef-440b-bf57-96f41d3bf04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li ng-star-inserted</value>
      <webElementGuid>3c673eae-5f31-4e93-96e6-7f11c49f84fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Purchase of Professional Service(s) </value>
      <webElementGuid>2e22f2f1-bde8-450a-bec9-124f8c646905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidepanel-body&quot;)/div[@class=&quot;padding-24 ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sw-stepper-content selected&quot;]/form[@class=&quot;ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;bg-gray-100 radius-md padding-24 margin-24&quot;]/div[@class=&quot;status-container&quot;]/sw-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;sw-select-wrapper&quot;]/div[@class=&quot;sw-select-dropdown ng-star-inserted&quot;]/div[@class=&quot;ul&quot;]/div[@class=&quot;li ng-star-inserted&quot;]</value>
      <webElementGuid>c53c3dad-3e92-4d50-8b07-89cf8a704200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidepanel-body']/div/sw-stepper/div/sw-stepper-content[2]/div[2]/form/div[2]/div/sw-select/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>45763101-014e-40f9-a071-66187434b7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase of Good(s)'])[1]/following::div[1]</value>
      <webElementGuid>bfe82b35-0588-48ba-94ad-039215d06a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Purpose of Payment*'])[1]/following::div[7]</value>
      <webElementGuid>f0c35bd6-e1dc-477f-ac4b-d8715e67f157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional fees payment(i.e. legal, accountant)'])[1]/preceding::div[1]</value>
      <webElementGuid>7a1ec0b1-9069-4dbf-ba48-8b16f38bace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll/Personnel Payment'])[1]/preceding::div[2]</value>
      <webElementGuid>6a0d7a3a-0535-473c-8116-38f79609c072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase of Professional Service(s)']/parent::*</value>
      <webElementGuid>8eee88a1-789c-478f-95e6-b9dd42b5c688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>06ebdf80-ca99-450d-9c24-0877abd761af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Purchase of Professional Service(s) ' or . = ' Purchase of Professional Service(s) ')]</value>
      <webElementGuid>10e4fbbe-906b-4812-bd74-b934910edf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
