<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectUSD</name>
   <tag></tag>
   <elementGuidId>232945ef-a5a3-46be-afe8-a5fe87b387c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a8ae833345ef-47 > div.flex.align-items-center.gaps-10.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the currency'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$USD&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>349870b2-4ece-48c3-8dcb-5d2908a52ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex align-items-center gaps-10 ng-star-inserted</value>
      <webElementGuid>68f59ebf-5d5f-41ce-a09a-23ee40915688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$USD</value>
      <webElementGuid>91b2f0fc-8475-4fd4-a211-00f9e92628cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a8ae833345ef-47&quot;)/div[@class=&quot;flex align-items-center gaps-10 ng-star-inserted&quot;]</value>
      <webElementGuid>a4b9c5b8-ee23-4286-a6d7-f9ba47a19c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a8ae833345ef-47']/div</value>
      <webElementGuid>adb93b73-83a0-4368-b1ee-2f655e312136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the currency'])[1]/following::div[6]</value>
      <webElementGuid>f790c093-d8fa-4852-8c73-56827c3becb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter new name for wallet'])[1]/preceding::div[1]</value>
      <webElementGuid>1cad8dee-fbd4-4b43-8aa1-67901e5a1b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Wallet'])[2]/preceding::div[1]</value>
      <webElementGuid>e7988ee6-3128-4636-ab8a-c36b0bd87ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div</value>
      <webElementGuid>e41c2a27-a46f-4753-819e-3d529a49a7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$USD' or . = '$USD')]</value>
      <webElementGuid>74027913-225b-4097-a04b-788698b8f21a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
