<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WtB_SelectPurpose</name>
   <tag></tag>
   <elementGuidId>c77df6dd-7589-47ab-808a-733462048258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#af3f812dccc7-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='af3f812dccc7-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Purchase of Good(s)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f8b648d-ab88-44f6-a222-5604f96fb0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>e5a237c6-f8b8-4271-a674-f4ae19161438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bac45c17-ffc1-4dc4-a34f-3353db092921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>af3f812dccc7-0</value>
      <webElementGuid>4fb468d1-c63e-44bc-ab0a-04309cd77524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase of Good(s)</value>
      <webElementGuid>98ac2c84-4778-461f-b22c-8f0c02b6c18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;af3f812dccc7-0&quot;)</value>
      <webElementGuid>2ba71bb2-e9e9-4c33-8d45-1f18fe1f1081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af3f812dccc7-0']</value>
      <webElementGuid>0bc77c18-1bb6-4686-8573-e852d56af108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af3f812dccc7']/div/div[2]/div</value>
      <webElementGuid>f99b399a-dbd3-49b6-b984-d72d2bd57c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Purpose of Payment'])[1]/following::div[5]</value>
      <webElementGuid>bff6b0b3-cc8f-4295-92c6-eb03d390cab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purpose of Payment'])[1]/following::div[8]</value>
      <webElementGuid>4211d836-fc5c-432f-9e38-53b91d74a34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase of Professional Service(s)'])[1]/preceding::div[1]</value>
      <webElementGuid>e5ebe2a2-e37d-444e-93fe-609a6c543045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>49f16ac1-babd-43c6-876b-20a4498a018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af3f812dccc7-0' and (text() = 'Purchase of Good(s)' or . = 'Purchase of Good(s)')]</value>
      <webElementGuid>8df23ca0-a6d8-4a3c-9e16-e3362888ed9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
