<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WtB_EUR</name>
   <tag></tag>
   <elementGuidId>895f7348-0dae-432d-ad23-a3496a0eb584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;a1c08d0af2fe-0&quot;)/div[@class=&quot;dropdown-option flex justify-content-between gaps-10 ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-option.flex.justify-content-between.gaps-10.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a1c08d0af2fe-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='a1c08d0af2fe-0']/div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>624f6a31-3d1f-4e7c-99aa-7d91692ab6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-option flex justify-content-between gaps-10 ng-star-inserted</value>
      <webElementGuid>93a15fad-831c-4559-9ea8-82a8b3d598a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>€ EUR Default EUR Wallet € 5745.25 </value>
      <webElementGuid>027e76a6-f1fa-462a-b7f9-bd78b43bf755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1c08d0af2fe-0&quot;)/div[@class=&quot;dropdown-option flex justify-content-between gaps-10 ng-star-inserted&quot;]</value>
      <webElementGuid>e731d368-adce-42c9-8986-4d7889fc90dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a1c08d0af2fe-0']/div</value>
      <webElementGuid>7e71cc42-c7f1-4ed9-ba46-58f68df3d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search curreny wallets'])[1]/following::div[8]</value>
      <webElementGuid>ef320b9e-f215-4553-a72b-01f17a1e55b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction'])[1]/following::div[23]</value>
      <webElementGuid>448622db-72b9-495a-8e43-7e84a247d20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£'])[2]/preceding::div[53]</value>
      <webElementGuid>760b9306-0d39-4edc-ac4c-c285d60be5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£'])[3]/preceding::div[55]</value>
      <webElementGuid>c05735ab-cc34-4e4c-8808-a89588aa9c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div</value>
      <webElementGuid>29c7bac1-5370-4815-bfe9-5023f5dbe1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '€ EUR Default EUR Wallet € 5745.25 ' or . = '€ EUR Default EUR Wallet € 5745.25 ')]</value>
      <webElementGuid>28ae094e-a9fb-4735-b60a-34d4fad6ac5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
