<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WtB_AuthOTP</name>
   <tag></tag>
   <elementGuidId>5df55925-ce1f-4d82-87bd-3ba1f27da42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sw-input[name=&quot;otp&quot;] > span > #swap-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='swap-input'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form #swap-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cafb0005-bf24-4875-b98c-c93f4cb41d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ff02fd9e-1eec-43bd-8740-33948bf6fbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>61f9c508-7d7f-49b3-ae6c-8cdcad90bef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9fcc1dd-443b-499f-bacf-d2930ffaa4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>a7768d4f-0656-4049-97a4-4513d156497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>6493a330-31ba-491c-b1f7-94e3587615f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>61a0cda4-5d52-418d-8488-35828172863d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>458ea7d4-c408-4b52-ab2f-d2fe3dd4d5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d{6}$/</value>
      <webElementGuid>e3db1fed-1d04-4f41-82f4-a0cdfd9f452b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/modal-container[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog inline-padding modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/v-verify[1]/form[@class=&quot;mt-3 ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;margin-block-16&quot;]/sw-input[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/span[1]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>6f0df314-857a-461d-b589-ad84c94eb315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='swap-input'])[3]</value>
      <webElementGuid>bf7c77d8-09a0-430d-84fa-10b2c2a72c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/sw-input/span/input</value>
      <webElementGuid>bb917276-a69c-4d85-86cc-41f2c091336d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'text']</value>
      <webElementGuid>93786b9a-25c5-4f51-a06d-4d84aaec6229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
