<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WtB_BeneSearch</name>
   <tag></tag>
   <elementGuidId>c0673491-4884-47f1-8b5a-0005ceaf166f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swap-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='swap-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=searchbox[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70dba1e9-c1ca-4e89-8e8d-39567d5cf109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sw-input ng-valid ng-touched ng-dirty</value>
      <webElementGuid>d780a11a-bd4e-46d6-945f-907e9e4eebd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swap-input</value>
      <webElementGuid>e1f414b8-b658-4e09-ad14-85a62a496d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b8a5a28c-3913-4c4a-ae54-f6bd0e0e4482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>0bf44501-529c-43c7-95cc-412decb3df8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>979463c4-81ae-4c69-8ffd-9791d54759f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>8a3a8906-7c31-43fb-9d51-2734d9d567a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>e2834f5d-fb32-4679-b9b5-bd470cfa85b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4eca183b-5a1e-4ec2-8f8c-376201ff7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/v-main-bridge[@class=&quot;ng-star-inserted&quot;]/v-main[@class=&quot;ng-star-inserted&quot;]/v-client-main[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main light ng-star-inserted&quot;]/div[@class=&quot;content light&quot;]/div[@class=&quot;flex flex-column w-full main-content&quot;]/div[@class=&quot;content-wrapper light&quot;]/v-send-money[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flex flex-column gaps-16&quot;]/v-send-money-core[1]/div[@class=&quot;panel-body ng-star-inserted&quot;]/sw-stepper[1]/div[@class=&quot;sw-stepper-wrapper&quot;]/sw-stepper-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sw-stepper-content selected&quot;]/div[@class=&quot;sw-card ng-star-inserted&quot;]/v-select-recipient[1]/sw-card[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;sw-card bg-white text-gray-800&quot;]/sw-card-body[1]/div[@class=&quot;sw-card-body bg-gray-100 padding-16&quot;]/div[@class=&quot;radius-md bg-white padding-16&quot;]/div[@class=&quot;margin-block-16 ng-star-inserted&quot;]/sw-table[1]/div[@class=&quot;sw-table-card&quot;]/div[@class=&quot;sw-table-card-header ng-star-inserted&quot;]/div[@class=&quot;flex space-between flex-wrap align-items-center ng-star-inserted&quot;]/div[@class=&quot;full-width-mobile flex gaps-16 flex-wrap&quot;]/div[@class=&quot;full-width-mobile&quot;]/sw-input[@class=&quot;ng-untouched ng-valid ng-dirty&quot;]/span[@class=&quot;sw-icon-left&quot;]/input[@id=&quot;swap-input&quot;]</value>
      <webElementGuid>f4d80014-2c7e-4876-9f12-eee7f2c4c78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='swap-input']</value>
      <webElementGuid>1ba98873-93d8-41f0-a2d3-24f2a86e834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>614a2946-506e-4816-969f-bcfb016b0e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swap-input' and @type = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>72cd4bff-1944-42c8-b60e-e3da7e1263e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
